# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ccea7b61f57c09502e8c190eb2d16bd58e523a70357e65a76ff48a63894fb7c6e2262c134b50764e0d58b1f879e904e13dace46fac6d2c609fc14aad764065

test:
  secret_key_base: 0d2bc86c62969d96f09e6b27d2160d55f1a3620efd086ba109fe712a06feecfc2d484fcbd6a2f51b70970d55119adbe2925b83a90ba97c738360ed2e2114ea99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
